import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { sendEmail, adminRequestEmail } from "@/lib/email";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const ADMIN_EMAIL = "infizium@outlook.com";
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://infizium-app.vercel.app";

export async function POST(req: NextRequest) {
  try {
    const { email, role, personaDetail, message, schoolName } = await req.json();

    if (!email || !role) {
      return NextResponse.json({ error: "Email and role are required." }, { status: 400 });
    }

    // Block duplicate pending requests from the same email
    const { data: existing } = await supabaseAdmin
      .from("access_requests")
      .select("id, status")
      .eq("email", email.toLowerCase())
      .eq("status", "pending")
      .maybeSingle();

    if (existing) {
      return NextResponse.json(
        { error: "You already have a pending request. Check your inbox for updates." },
        { status: 409 }
      );
    }

    // Create the request record (token auto-generated by DB default)
    const { data: request, error: insertErr } = await supabaseAdmin
      .from("access_requests")
      .insert({
        email: email.toLowerCase(),
        role,
        persona_detail: personaDetail ?? null,
        message: message ?? null,
        school_name: schoolName ?? null,
      })
      .select("id, token")
      .single();

    if (insertErr || !request) {
      console.error("[request-access] insert error:", insertErr);
      return NextResponse.json({ error: "Could not save request. Try again." }, { status: 500 });
    }

    const approveUrl = `${APP_URL}/api/auth/approve/${request.token}`;
    const denyUrl = `${APP_URL}/api/auth/deny/${request.token}`;

    await sendEmail({
      to: ADMIN_EMAIL,
      subject: `Infizium access request — ${role} · ${email}`,
      html: adminRequestEmail({ email, role, personaDetail: personaDetail ?? "", message: message ?? "", schoolName: schoolName ?? "", approveUrl, denyUrl }),
    });

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[request-access]", err);
    return NextResponse.json({ error: "Internal error." }, { status: 500 });
  }
}
